export const featureData = [
  {
    id: "1",
    featureLogo: require("../../assets/images/seacrh.png"),
    featureName: "Search",
    featureAbt:
      "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
  },
  {
    id: "2",
    featureLogo: require("../../assets/images/select.png"),
    featureName: "Select",
    featureAbt:
      "Choose from thousands of options generated by the slogan maker that fit your needs.",
  },
  {
    id: "3",
    featureLogo: require("../../assets/images/stand-out.png"),
    featureName: "Stand out",
    featureAbt: "Congrats on your new slogan. It's time to win the world!",
  },
];
